language: go

install:
  - git config --global http.followRedirects true
  - git clone --depth 1 http://h12.io/socks /home/travis/gopath/src/h12.io/socks
  - go get -t -v ./...

script:
  - go test -v ./...
  - bash -x ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
